; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = production
extra_configs = secrets.ini

[env:esp32s3-dev-module]
platform = espressif32@6.4.0
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

test_build_src = true

lib_ldf_mode = deep+

lib_deps = 
	adafruit/DHT sensor library@^1.4.6
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^3.11.0
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.5
	claws/BH1750@^1.3.0
	adafruit/Adafruit NeoPixel@^1.12.0
	WebServer



[env:production]
extends = env:esp32s3-dev-module
build_flags = 
	${env:esp32s3-dev-module.build_flags}
	-DLOG_LEVEL=3   ; LOG_LEVEL_INFO
	-O2             ; Optimization Level 2
	-DNDEBUG        ; Disable standard assertions
    ; Inject Secrets from secrets.ini
    ; Pass as bare tokens, will be stringified in secrets.h
    '-DSECRET_WIFI_AP_NAME=${secrets.wifi_ap_name}'
    '-DSECRET_WIFI_AP_PASS=${secrets.wifi_ap_pass}'
    '-DSECRET_NETPIE_CLIENT_ID=${secrets.netpie_client_id}'
    '-DSECRET_NETPIE_TOKEN=${secrets.netpie_token}'
    '-DSECRET_NETPIE_SECRET=${secrets.netpie_secret}'
    '-DSECRET_OTA_PASSWORD=${secrets.ota_password}'
    '-DSECRET_TELNET_PASSWORD=${secrets.telnet_password}'

board_build.f_cpu = 240000000L ; Max Performance (240MHz)

[env:ota_upload]
extends = env:production
upload_protocol = espota
upload_port = aquaponics-sensor.local           ; Pi hostname (auto-resolve IP, forwards to ESP32 via NAT)
upload_flags = 
	--auth=${secrets.ota_password}       ; รหัสจาก secrets.ini
	--port=3232

[env:native]
platform = native
test_framework = unity
test_ignore = test_native
build_flags = 
	-std=gnu++11
	-I test/test_native/mock
	-I test/common


